version: '3.8'

services:
  dev:
    container_name: nest
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 4000:4000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    restart: unless-stopped

  db:
    image: postgres
    container_name: nest-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pgfour
      - POSTGRES_USER=pgtwo
      - POSTGRES_PASSWORD=pgtwo
    networks:
      - nesjs-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - nesjs-network

networks:
  nesjs-network:
