version: '3.8'

services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 4000:4000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      #- /usr/src/app/node_modules
    restart: unless-stopped

  db:
    image: postgres
    container_name: nest_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pg
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
    networks:
      - nesjs-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - nesjs-network

networks:
  nesjs-network:
